version: "3"

services:
  rethinkdb:
    container_name: rethinkdb
    image: rethinkdb:2.4.2-bullseye-slim
    restart: unless-stopped
    volumes:
        - "rethinkdb-data:/data"
    command: "rethinkdb --bind all --cache-size 2048"

  adb:
    container_name: adb
    image: gounthar/docker-adb:aarch64
    restart: unless-stopped
    volumes: 
      - "/dev/bus/usb:/dev/bus/usb"
    privileged: true

  stf:
    container_name: stf
    build:
      context: .
      dockerfile: Dockerfile-debian-arm64
    ports:
      - "7100:7100"
      - "7110:7110"
      - "7400-7500:7400-7500"
    environment:
      - TZ='America/Los_Angeles'
      - RETHINKDB_PORT_28015_TCP=tcp://rethinkdb:28015
      - STF_PROVIDER_SCREEN_FRAME_RATE=10
      - STF_PROVIDER_SCREEN_JPEG_QUALITY=40
    restart: unless-stopped
    command: stf local --adb-host adb --public-ip [YOUR_LOCAL_IP] --provider-min-port 7400 --provider-max-port 7500

volumes:
  rethinkdb-data: {}
